/****** Object:  Table [dbo].[_backup_servico_20210519]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[_backup_servico_20210519](
	[CD_SERVICO] [int] NOT NULL,
	[NM_SERVICO] [varchar](200) NULL,
	[tp_procedimento] [smallint] NOT NULL,
	[cd_exigedocumentacao] [bit] NOT NULL,
	[cd_naoapresentaodontograma] [bit] NOT NULL,
	[cd_naoaceitapendente] [bit] NOT NULL,
	[fl_urgencia] [bit] NOT NULL,
	[fl_aceitainclusaodireta] [bit] NOT NULL,
	[fl_urgencia_noturna] [bit] NOT NULL,
	[cd_servico_antigo] [varchar](200) NULL,
	[fl_ApresentaProdutividade] [bit] NOT NULL,
	[fl_DesprezaMarcacao] [bit] NOT NULL,
	[fl_ContagemBaixaAgenda] [bit] NOT NULL,
	[cd_especialidadereferencia] [int] NOT NULL,
	[qt_face_dente] [tinyint] NULL,
	[fl_exige_dente] [bit] NULL,
	[fl_recorrente] [bit] NULL,
	[cd_peso] [float] NULL,
	[fl_restringePericia] [bit] NULL,
	[cd_servicoANS] [int] NULL,
	[vl_us] [money] NULL,
	[cd_tabelaANS] [varchar](2) NULL,
	[fl_IncluirCorrelacionados] [bit] NULL,
	[fl_BaixaFinalOdontograma] [bit] NULL,
	[cd_grupo] [int] NULL,
	[qt_peso_sip] [smallint] NULL,
	[cd_Servico_coparticipado] [int] NULL,
	[realizacaoQualquerPrestador] [tinyint] NULL,
	[aceitaOrcamento] [bit] NULL,
	[qtDiasBloqueio] [int] NULL,
	[baixarApenasAposUpload] [bit] NULL,
	[lancarApenasComEspecialidade] [bit] NULL,
	[procedimentosCorrelacionados] [varchar](max) NULL,
	[cd_tipo_documentacao] [smallint] NULL,
	[dente] [bit] NULL,
	[solicitanteLancamento] [tinyint] NULL,
	[idTipoAnaliseAuditoria] [tinyint] NULL,
	[realizarAposLiberacaoManual] [bit] NULL,
	[permiteDuplicadoGto] [bit] NULL,
	[permiteDuplicadoProdutividadeAndamento] [bit] NULL,
	[liberadoAutomaticamenteRealizacao] [bit] NULL,
	[periciaFinal] [bit] NULL,
	[menuNecessidades] [bit] NULL,
	[exigeLaboratorioProtese] [bit] NULL,
	[permiteEmDentesAusentes] [bit] NULL,
	[tempoMinutosMedioRealizacao] [float] NULL,
	[flanalisaProcedimentoPag] [bit] NULL,
	[idGrupoTratamento] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
