/****** Object:  Table [dbo].[_Procedimentos]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[_Procedimentos](
	[TUSS] [float] NULL,
	[Descricao] [nvarchar](255) NULL,
	[Tipo] [float] NULL,
	[Documentacao] [float] NULL,
	[Exige_dente] [nvarchar](255) NULL,
	[Qtde_Faces] [nvarchar](255) NULL,
	[Especialidade] [float] NULL,
	[Urgencia] [nvarchar](255) NULL,
	[ASAI] [nvarchar](255) NULL,
	[AS] [nvarchar](255) NULL,
	[AI] [nvarchar](255) NULL,
	[HASD] [nvarchar](255) NULL,
	[HASE] [nvarchar](255) NULL,
	[HAID] [nvarchar](255) NULL,
	[HAIE] [nvarchar](255) NULL,
	[RMD] [nvarchar](255) NULL,
	[RME] [nvarchar](255) NULL,
	[RPD] [nvarchar](255) NULL,
	[RPE] [nvarchar](255) NULL,
	[S1] [nvarchar](255) NULL,
	[S2] [nvarchar](255) NULL,
	[S3] [nvarchar](255) NULL,
	[S4] [nvarchar](255) NULL,
	[S5] [nvarchar](255) NULL,
	[S6] [nvarchar](255) NULL,
	[DIAGNOSTICO ] [nvarchar](255) NULL,
	[PREVENÇÃO] [nvarchar](255) NULL,
	[ODONTOPEDIATRIA] [nvarchar](255) NULL,
	[DENTÍSTICA] [nvarchar](255) NULL,
	[ENDODONTIA] [nvarchar](255) NULL,
	[PERIODONTIA] [nvarchar](255) NULL,
	[PRÓTESE] [nvarchar](255) NULL,
	[CIRURGIA] [nvarchar](255) NULL,
	[ORTODONTIA] [nvarchar](255) NULL,
	[ESTÉTICA] [nvarchar](255) NULL,
	[RADIOLOGIA] [nvarchar](255) NULL,
	[URGÊNCIA DIURNA] [nvarchar](255) NULL,
	[URGÊNCIA NOTURNA] [nvarchar](255) NULL,
	[IMPLANTE] [nvarchar](255) NULL,
	[CIRURGIA BUCO MAXILO FACIAL] [nvarchar](255) NULL,
	[CLÍNICO GERAL] [nvarchar](255) NULL,
	[TESTE E EXAME DE LABORATÓRIO] [nvarchar](255) NULL
) ON [PRIMARY]
