/****** Object:  Table [dbo].[ABRANGENCIA_COLABORADOR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ABRANGENCIA_COLABORADOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_ABRANGENCIA] [int] NULL,
	[CD_FUNCIONARIO] [int] NULL
) ON [PRIMARY]
