/****** Object:  Table [dbo].[AUDITORIA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUDITORIA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Dt_Atualizacao] [datetime] NULL,
	[Login] [varchar](100) NULL,
	[Hostname] [varchar](100) NULL,
	[Operacao] [varchar](20) NULL,
	[CD_PARCELA] [int] NOT NULL,
	[CD_ASSOCIADO_empresa] [int] NOT NULL,
	[TP_ASSOCIADO_EMPRESA] [smallint] NOT NULL,
	[cd_tipo_parcela] [smallint] NOT NULL,
	[CD_TIPO_PAGAMENTO] [int] NOT NULL,
	[CD_TIPO_RECEBIMENTO] [int] NOT NULL,
	[NOSSO_NUMERO] [varchar](50) NULL,
	[DT_VENCIMENTO] [datetime] NOT NULL,
	[DT_PAGAMENTO] [datetime] NULL,
	[DT_GERADO] [datetime] NOT NULL,
	[DT_IMPRESSO] [datetime] NULL,
	[DT_BAIXA] [datetime] NULL,
	[VL_PARCELA] [money] NOT NULL,
	[VL_Acrescimo] [money] NULL,
	[VL_Desconto] [money] NULL,
	[VL_SERVICO] [money] NULL,
	[VL_PAGO] [money] NULL,
	[CD_USUARIO_BAIXA] [int] NULL,
	[CD_USUARIO_ALTERACAO] [int] NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[cd_lote_processo_banco] [int] NULL,
	[VL_JurosMultaReferencia] [money] NULL,
	[chaId] [int] NULL,
	[chaId_retorno_corresp] [int] NULL,
	[Chave] [varchar](50) NULL,
	[NF] [bigint] NULL,
	[cd_usuario_cadastro] [int] NULL,
	[lnfId] [int] NULL,
	[NFeRPS] [varchar](50) NULL,
	[vl_referenciaNF] [money] NULL,
	[dt_vencimento_new] [datetime] NULL,
	[obs] [varchar](500) NULL,
	[vl_imposto] [money] NULL,
	[vl_desconto_recebimento] [money] NULL,
	[vl_taxa] [money] NULL,
	[vl_titulo] [money] NULL,
	[vl_multa] [money] NULL,
	[dt_cancelado_contabil] [date] NULL,
	[VL_AcrescimoAvulso] [money] NULL,
	[VL_DescontoAvulso] [money] NULL,
	[VL_Final] [money] NULL,
	[linkNota] [varchar](300) NULL,
	[dt_negociado] [date] NULL,
	[obsNF] [varchar](500) NULL,
	[dt_credito] [datetime] NULL,
	[dt_emissao] [datetime] NULL,
	[cd_ParcelaOriginal] [int] NULL,
	[obsBoleto] [varchar](500) NULL,
	[dt_inicio_cobertura] [date] NULL,
	[cd_empresaGerado] [bigint] NULL,
	[executarTrigger] [bit] NULL,
	[cd_sequencial_lote_boleto] [int] NULL,
	[dentistaOrcamento] [int] NULL,
	[vendedorOrcamento] [int] NULL,
	[exibir] [bit] NULL,
	[cd_lote_processo_banco_baixa] [int] NULL,
	[dataRemessa] [datetime] NULL,
	[dt_visualizacaoNF] [datetime] NULL,
	[parcelaProtestada] [bit] NULL,
	[dataParcelaProtestada] [datetime] NULL,
	[usuarioParcelaProtestada] [int] NULL,
	[exigeNF] [bit] NULL,
	[dataPagamentoTerceiro] [datetime] NULL,
	[cd_lote_processo_acatado] [int] NULL,
	[dentistaExecutorOrcamento] [int] NULL,
	[cancelamentoNfe] [int] NULL,
	[data_confirmacao_recebimento] [datetime] NULL,
	[usuario_confirmacao_recebimento] [int] NULL,
	[origem_informacao_confirmacao] [int] NULL,
	[vl_pagoTerceiro] [money] NULL,
	[idIntegracaoExterna] [varchar](50) NULL,
	[cd_lote_processo_banco_recebido] [int] NULL,
	[nfeErro] [varchar](200) NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[AUDITORIA] ADD  DEFAULT (getdate()) FOR [Dt_Atualizacao]
