/****** Object:  Table [dbo].[CRMAnexo]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CRMAnexo](
	[aneId] [int] IDENTITY(1,1) NOT NULL,
	[aneDescricao] [varchar](100) NOT NULL,
	[aneArquivo] [varchar](105) NOT NULL,
	[aneDtCadastro] [datetime] NOT NULL,
	[aneDtValidade] [datetime] NULL,
	[aneDtExclusao] [datetime] NULL,
	[TipoUsuario] [smallint] NOT NULL,
	[Usuario] [int] NOT NULL,
	[chaId] [int] NULL,
	[UsuarioExclusao] [int] NULL,
 CONSTRAINT [PK_CRMAnexo] PRIMARY KEY CLUSTERED 
(
	[aneId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_CRMAnexo] ON [dbo].[CRMAnexo]
(
	[chaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_CRMAnexo_1] ON [dbo].[CRMAnexo]
(
	[aneDtCadastro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_CRMAnexo_2] ON [dbo].[CRMAnexo]
(
	[aneDtValidade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[CRMAnexo] ADD  CONSTRAINT [DF_CRMAnexo_CRMTipoUsuario]  DEFAULT ((1)) FOR [TipoUsuario]
ALTER TABLE [dbo].[CRMAnexo]  WITH NOCHECK ADD  CONSTRAINT [FK_CRMAnexo_CRMChamado] FOREIGN KEY([chaId])
REFERENCES [dbo].[CRMChamado] ([chaId])
ALTER TABLE [dbo].[CRMAnexo] CHECK CONSTRAINT [FK_CRMAnexo_CRMChamado]
ALTER TABLE [dbo].[CRMAnexo]  WITH NOCHECK ADD  CONSTRAINT [FK_CRMAnexo_CRMTipoSolicitante] FOREIGN KEY([TipoUsuario])
REFERENCES [dbo].[CRMTipoSolicitante] ([tsoId])
ALTER TABLE [dbo].[CRMAnexo] CHECK CONSTRAINT [FK_CRMAnexo_CRMTipoSolicitante]
