/****** Object:  Table [dbo].[CRMAlertaSistema]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CRMAlertaSistema](
	[asiId] [int] IDENTITY(1,1) NOT NULL,
	[asiMensagem] [varchar](1000) NOT NULL,
	[asiUrl] [varchar](500) NULL,
	[asiDtCadastro] [datetime] NOT NULL,
	[usuario] [int] NOT NULL,
	[tipoUsuario] [smallint] NOT NULL,
	[chaId] [int] NULL,
 CONSTRAINT [PK_CRMAlerta] PRIMARY KEY CLUSTERED 
(
	[asiId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_CRMAlertaSistema] ON [dbo].[CRMAlertaSistema]
(
	[chaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_CRMAlertaSistema_1] ON [dbo].[CRMAlertaSistema]
(
	[tipoUsuario] ASC,
	[usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[CRMAlertaSistema]  WITH CHECK ADD  CONSTRAINT [FK_CRMAlertaSistema_CRMChamado] FOREIGN KEY([chaId])
REFERENCES [dbo].[CRMChamado] ([chaId])
ALTER TABLE [dbo].[CRMAlertaSistema] CHECK CONSTRAINT [FK_CRMAlertaSistema_CRMChamado]
