/****** Object:  Table [dbo].[DOMINIO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DOMINIO](
	[cd_dominio] [smallint] NOT NULL,
	[ds_dominio] [varchar](500) NOT NULL,
 CONSTRAINT [PK_DOMINIO] PRIMARY KEY NONCLUSTERED 
(
	[cd_dominio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
