/****** Object:  Table [dbo].[DOMINIO_VALOR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DOMINIO_VALOR](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[cd_dominio] [smallint] NOT NULL,
	[cd_sequencial] [int] NOT NULL,
	[vl_dominio] [varchar](500) NOT NULL,
	[ativo] [bit] NULL,
 CONSTRAINT [PK_DOMINIO_VALOR] PRIMARY KEY NONCLUSTERED 
(
	[id] ASC,
	[cd_dominio] ASC,
	[cd_sequencial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DOMINIO_VALOR]  WITH NOCHECK ADD  CONSTRAINT [FK_DOMINIO_VALOR_DOMINIO] FOREIGN KEY([cd_dominio])
REFERENCES [dbo].[DOMINIO] ([cd_dominio])
ALTER TABLE [dbo].[DOMINIO_VALOR] CHECK CONSTRAINT [FK_DOMINIO_VALOR_DOMINIO]
