/****** Object:  Table [dbo].[ERROS_TISS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERROS_TISS](
	[errCod] [float] NOT NULL,
	[errDescricao] [nvarchar](255) NULL,
 CONSTRAINT [PK_ERROS_TISS] PRIMARY KEY CLUSTERED 
(
	[errCod] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
