/****** Object:  Table [dbo].[FORNECEDORES_CONTAS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FORNECEDORES_CONTAS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[cd_fornecedor] [int] NOT NULL,
	[sequencial_conta] [int] NOT NULL,
 CONSTRAINT [PK_FORNECEDORES_CONTAS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[FORNECEDORES_CONTAS]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_CONTAS_FORNECEDORES] FOREIGN KEY([cd_fornecedor])
REFERENCES [dbo].[FORNECEDORES] ([CD_FORNECEDOR])
ALTER TABLE [dbo].[FORNECEDORES_CONTAS] CHECK CONSTRAINT [FK_FORNECEDORES_CONTAS_FORNECEDORES]
ALTER TABLE [dbo].[FORNECEDORES_CONTAS]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_CONTAS_TB_Conta] FOREIGN KEY([sequencial_conta])
REFERENCES [dbo].[TB_Conta] ([Sequencial_Conta])
ALTER TABLE [dbo].[FORNECEDORES_CONTAS] CHECK CONSTRAINT [FK_FORNECEDORES_CONTAS_TB_Conta]
