/****** Object:  Table [dbo].[FORNECEDORES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FORNECEDORES](
	[CD_FORNECEDOR] [int] IDENTITY(1,1) NOT NULL,
	[NM_FORNECEDOR] [varchar](100) NOT NULL,
	[NR_CPF] [varchar](11) NULL,
	[NR_CGC] [varchar](14) NULL,
	[EndLogradouro] [varchar](50) NULL,
	[baiId] [int] NULL,
	[ufId] [smallint] NULL,
	[cd_municipio] [int] NULL,
	[nm_contato] [varchar](50) NULL,
	[Cep] [varchar](8) NULL,
	[CHAVE_TIPOLOGRADOURO] [int] NULL,
	[EndNumero] [int] NULL,
	[EndComplemento] [varchar](50) NULL,
	[fl_ativo] [bit] NOT NULL,
	[cd_contabilidade] [int] NULL,
	[nm_titular_cta] [varchar](150) NULL,
	[cd_banco] [int] NULL,
	[nr_agencia] [varchar](30) NULL,
	[nr_conta] [varchar](30) NULL,
	[nr_cpf_titular] [varchar](11) NULL,
	[cnpj_banco] [varchar](14) NULL,
	[tipo_conta] [bit] NULL,
	[conta_operacao] [int] NULL,
	[nm_fantasia] [varchar](200) NULL,
	[observacao] [varchar](500) NULL,
 CONSTRAINT [PK_FORNECEDORES] PRIMARY KEY CLUSTERED 
(
	[CD_FORNECEDOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_Bairro] FOREIGN KEY([baiId])
REFERENCES [dbo].[Bairro] ([baiId])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_Bairro]
ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_Contabilidade] FOREIGN KEY([cd_contabilidade])
REFERENCES [dbo].[Contabilidade] ([cd_contabilidade])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_Contabilidade]
ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_MUNICIPIO] FOREIGN KEY([cd_municipio])
REFERENCES [dbo].[MUNICIPIO] ([CD_MUNICIPIO])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_MUNICIPIO]
ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_TB_Banco_Contratos] FOREIGN KEY([cd_banco])
REFERENCES [dbo].[TB_Banco_Contratos] ([cd_banco])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_TB_Banco_Contratos]
ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_TB_TIPOLOGRADOURO] FOREIGN KEY([CHAVE_TIPOLOGRADOURO])
REFERENCES [dbo].[TB_TIPOLOGRADOURO] ([CHAVE_TIPOLOGRADOURO])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_TB_TIPOLOGRADOURO]
ALTER TABLE [dbo].[FORNECEDORES]  WITH CHECK ADD  CONSTRAINT [FK_FORNECEDORES_UF] FOREIGN KEY([ufId])
REFERENCES [dbo].[UF] ([ufId])
ALTER TABLE [dbo].[FORNECEDORES] CHECK CONSTRAINT [FK_FORNECEDORES_UF]
