/****** Object:  Table [dbo].[FUNCIONARIO_GRUPO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FUNCIONARIO_GRUPO](
	[cd_funcionario] [int] NOT NULL,
	[gfuId] [int] NOT NULL,
 CONSTRAINT [PK_FUNCIONARIO_GRUPO] PRIMARY KEY CLUSTERED 
(
	[cd_funcionario] ASC,
	[gfuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[FUNCIONARIO_GRUPO]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNCIONARIO_GRUPO_GrupoFuncionario] FOREIGN KEY([gfuId])
REFERENCES [dbo].[GrupoFuncionario] ([gfuId])
ALTER TABLE [dbo].[FUNCIONARIO_GRUPO] CHECK CONSTRAINT [FK_FUNCIONARIO_GRUPO_GrupoFuncionario]
