/****** Object:  Table [dbo].[FUNCIONARIO_ESPECIALIDADE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FUNCIONARIO_ESPECIALIDADE](
	[CD_FUNCIONARIO] [int] NOT NULL,
	[CD_ESPECIALIDADE] [int] NOT NULL,
	[cd_usuario] [varchar](50) NULL,
	[dt_usuario] [datetime] NULL,
	[sequencial] [int] IDENTITY(1,1) NOT NULL,
	[percentualRepasse] [varchar](50) NULL,
 CONSTRAINT [PK_FUNCIONARIO_ESPECIALIDADE] PRIMARY KEY CLUSTERED 
(
	[CD_FUNCIONARIO] ASC,
	[CD_ESPECIALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_FUNCIONARIO_ESPECIALIDADE] ON [dbo].[FUNCIONARIO_ESPECIALIDADE]
(
	[CD_ESPECIALIDADE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_FUNCIONARIO_ESPECIALIDADE_1] ON [dbo].[FUNCIONARIO_ESPECIALIDADE]
(
	[CD_FUNCIONARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[FUNCIONARIO_ESPECIALIDADE]  WITH NOCHECK ADD  CONSTRAINT [FK_FUNCIONARIO_ESPECIALIDADE_especialidade] FOREIGN KEY([CD_ESPECIALIDADE])
REFERENCES [dbo].[ESPECIALIDADE] ([cd_especialidade])
ALTER TABLE [dbo].[FUNCIONARIO_ESPECIALIDADE] CHECK CONSTRAINT [FK_FUNCIONARIO_ESPECIALIDADE_especialidade]
