/****** Object:  Table [dbo].[GrupoAnalise]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[GrupoAnalise](
	[CD_GRUPOAnalise] [smallint] IDENTITY(1,1) NOT NULL,
	[NM_GRUPOAnalise] [varchar](50) NOT NULL,
 CONSTRAINT [PK_GrupoAnalise] PRIMARY KEY CLUSTERED 
(
	[CD_GRUPOAnalise] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
