/****** Object:  Table [dbo].[GTOLote]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[GTOLote](
	[gloId] [int] IDENTITY(1,1) NOT NULL,
	[gloDtCadastro] [datetime] NOT NULL,
	[cd_funcionarioCadastro] [int] NOT NULL,
	[cd_funcionarioDentista] [int] NOT NULL,
	[cd_filial] [int] NOT NULL,
	[gloProtocolo] [varchar](50) NOT NULL,
	[gloGTO] [varchar](50) NULL,
	[gloDtImpressao] [datetime] NULL,
	[gtoUrgencia] [bit] NULL,
	[gorId] [tinyint] NULL,
	[cd_sequencialAgenda] [int] NULL,
	[gloOBS] [varchar](500) NULL,
	[gtiId] [tinyint] NULL,
	[gloDtAutorizacao] [datetime] NULL,
	[gloDtValidade] [datetime] NULL,
	[gloGuiaExterna] [varchar](50) NULL,
 CONSTRAINT [PK_GTOLote] PRIMARY KEY CLUSTERED 
(
	[gloId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_GTOLote_7_52155927__K7_2] ON [dbo].[GTOLote]
(
	[gloGTO] ASC
)
INCLUDE([gloDtCadastro]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_GTOLote] ON [dbo].[GTOLote]
(
	[gloGTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_GTOLote_1] ON [dbo].[GTOLote]
(
	[gloProtocolo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_GTOLote_2] ON [dbo].[GTOLote]
(
	[cd_funcionarioDentista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_GTOLote_3] ON [dbo].[GTOLote]
(
	[cd_filial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[GTOLote]  WITH CHECK ADD  CONSTRAINT [FK_GTOLote_cd_sequencialAgenda] FOREIGN KEY([cd_sequencialAgenda])
REFERENCES [dbo].[agenda] ([cd_sequencial])
ALTER TABLE [dbo].[GTOLote] CHECK CONSTRAINT [FK_GTOLote_cd_sequencialAgenda]
ALTER TABLE [dbo].[GTOLote]  WITH CHECK ADD  CONSTRAINT [FK_GTOLote_FILIAL] FOREIGN KEY([cd_filial])
REFERENCES [dbo].[FILIAL] ([cd_filial])
ALTER TABLE [dbo].[GTOLote] CHECK CONSTRAINT [FK_GTOLote_FILIAL]
ALTER TABLE [dbo].[GTOLote]  WITH CHECK ADD  CONSTRAINT [FK_GTOLote_gorId] FOREIGN KEY([gorId])
REFERENCES [dbo].[GTOOrigem] ([gorId])
ALTER TABLE [dbo].[GTOLote] CHECK CONSTRAINT [FK_GTOLote_gorId]
ALTER TABLE [dbo].[GTOLote]  WITH CHECK ADD  CONSTRAINT [FK_GTOLote_GTOTipoImpressao] FOREIGN KEY([gtiId])
REFERENCES [dbo].[GTOTipoImpressao] ([gtiId])
ALTER TABLE [dbo].[GTOLote] CHECK CONSTRAINT [FK_GTOLote_GTOTipoImpressao]
