/****** Object:  Table [dbo].[HISTORICO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HISTORICO](
	[cd_sequencial] [int] IDENTITY(1,1) NOT NULL,
	[CD_SITUACAO] [smallint] NOT NULL,
	[CD_empresa] [bigint] NULL,
	[CD_SEQUENCIAL_dep] [int] NULL,
	[DT_SITUACAO] [date] NOT NULL,
	[NM_COMENTARIO] [nvarchar](300) NULL,
	[cd_usuario] [int] NULL,
	[cd_MOTIVO_CANCELAMENTO] [int] NULL,
	[Vl_Mensalidade] [money] NULL,
	[cd_sequencial_historico_origem] [int] NULL,
	[dt_fim_atendimento] [datetime] NULL,
	[cd_empresaDependente] [bigint] NULL,
	[chaid] [int] NULL,
	[ds_observacao_recibo] [varchar](max) NULL,
	[flBloqueioAgendaConsulta] [bit] NULL,
	[flAcordarParcelas] [bit] NULL,
 CONSTRAINT [PK_HISTORICO] PRIMARY KEY NONCLUSTERED 
(
	[cd_sequencial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_HISTORICO_5_1597665185__K1D_2_3_5] ON [dbo].[HISTORICO]
(
	[cd_sequencial] DESC
)
INCLUDE([CD_SITUACAO],[CD_empresa],[DT_SITUACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_HISTORICO_5_1597665185__K1D_2_3_6] ON [dbo].[HISTORICO]
(
	[cd_sequencial] DESC
)
INCLUDE([CD_SITUACAO],[CD_SEQUENCIAL_dep],[DT_SITUACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_HISTORICO_5_1597665185__K3_K1_5] ON [dbo].[HISTORICO]
(
	[CD_empresa] ASC,
	[cd_sequencial] ASC
)
INCLUDE([DT_SITUACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_HISTORICO_5_1597665185__K3_K1_6] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[cd_sequencial] ASC
)
INCLUDE([DT_SITUACAO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_10] ON [dbo].[HISTORICO]
(
	[CD_SITUACAO] ASC,
	[DT_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_11] ON [dbo].[HISTORICO]
(
	[DT_SITUACAO] DESC,
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_12] ON [dbo].[HISTORICO]
(
	[DT_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_13] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[DT_SITUACAO] DESC,
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_14] ON [dbo].[HISTORICO]
(
	[CD_empresa] ASC,
	[DT_SITUACAO] DESC,
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_15] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[DT_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_16] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_17] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[cd_sequencial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_18] ON [dbo].[HISTORICO]
(
	[CD_empresa] ASC,
	[cd_sequencial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_ix_historico_19] ON [dbo].[HISTORICO]
(
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO] ON [dbo].[HISTORICO]
(
	[DT_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_1] ON [dbo].[HISTORICO]
(
	[CD_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_2] ON [dbo].[HISTORICO]
(
	[CD_empresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_3] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_4] ON [dbo].[HISTORICO]
(
	[cd_MOTIVO_CANCELAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_5] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[DT_SITUACAO] DESC,
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_6] ON [dbo].[HISTORICO]
(
	[CD_empresa] ASC,
	[DT_SITUACAO] DESC,
	[cd_sequencial] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_HISTORICO_7] ON [dbo].[HISTORICO]
(
	[CD_SEQUENCIAL_dep] ASC,
	[DT_SITUACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK__HISTORICO__chaid__2BC05AFC] FOREIGN KEY([chaid])
REFERENCES [dbo].[CRMChamado] ([chaId])
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK__HISTORICO__chaid__2BC05AFC]
ALTER TABLE [dbo].[HISTORICO]  WITH NOCHECK ADD  CONSTRAINT [FK_HISTORICO_DEPENDENTES] FOREIGN KEY([CD_SEQUENCIAL_dep])
REFERENCES [dbo].[DEPENDENTES] ([CD_SEQUENCIAL])
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_DEPENDENTES]
ALTER TABLE [dbo].[HISTORICO]  WITH NOCHECK ADD  CONSTRAINT [FK_HISTORICO_EMPRESA] FOREIGN KEY([CD_empresa])
REFERENCES [dbo].[EMPRESA] ([CD_EMPRESA])
ON UPDATE CASCADE
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_EMPRESA]
ALTER TABLE [dbo].[HISTORICO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORICO_EMPRESA_DEPENDENTE] FOREIGN KEY([cd_empresaDependente])
REFERENCES [dbo].[EMPRESA] ([CD_EMPRESA])
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_EMPRESA_DEPENDENTE]
ALTER TABLE [dbo].[HISTORICO]  WITH NOCHECK ADD  CONSTRAINT [FK_HISTORICO_MOTIVO_CANCELAMENTO] FOREIGN KEY([cd_MOTIVO_CANCELAMENTO])
REFERENCES [dbo].[MOTIVO_CANCELAMENTO] ([cd_motivo_cancelamento])
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_MOTIVO_CANCELAMENTO]
ALTER TABLE [dbo].[HISTORICO]  WITH NOCHECK ADD  CONSTRAINT [FK_HISTORICO_SITUACAO_HISTORICO] FOREIGN KEY([CD_SITUACAO])
REFERENCES [dbo].[SITUACAO_HISTORICO] ([CD_SITUACAO_HISTORICO])
ALTER TABLE [dbo].[HISTORICO] CHECK CONSTRAINT [FK_HISTORICO_SITUACAO_HISTORICO]
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Situação|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'CD_SITUACAO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Empresa' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'CD_empresa'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Dependente' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'CD_SEQUENCIAL_dep'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Data|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'DT_SITUACAO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Comentário|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'NM_COMENTARIO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Usuario|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'cd_usuario'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Motivo' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'cd_MOTIVO_CANCELAMENTO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Valor Mensalidade|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'HISTORICO', @level2type=N'COLUMN',@level2name=N'Vl_Mensalidade'
