/****** Object:  Table [dbo].[MENSALIDADES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MENSALIDADES](
	[CD_PARCELA] [int] IDENTITY(1,1) NOT NULL,
	[CD_ASSOCIADO_empresa] [int] NOT NULL,
	[TP_ASSOCIADO_EMPRESA] [smallint] NOT NULL,
	[cd_tipo_parcela] [smallint] NOT NULL,
	[CD_TIPO_PAGAMENTO] [int] NOT NULL,
	[CD_TIPO_RECEBIMENTO] [int] NOT NULL,
	[NOSSO_NUMERO] [varchar](50) NULL,
	[DT_VENCIMENTO] [datetime] NOT NULL,
	[DT_PAGAMENTO] [datetime] NULL,
	[DT_GERADO] [datetime] NOT NULL,
	[DT_IMPRESSO] [datetime] NULL,
	[DT_BAIXA] [datetime] NULL,
	[VL_PARCELA] [money] NOT NULL,
	[VL_Acrescimo] [money] NULL,
	[VL_Desconto] [money] NULL,
	[VL_SERVICO] [money] NULL,
	[VL_PAGO] [money] NULL,
	[CD_USUARIO_BAIXA] [int] NULL,
	[CD_USUARIO_ALTERACAO] [int] NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[cd_lote_processo_banco] [int] NULL,
	[VL_JurosMultaReferencia] [money] NULL,
	[chaId] [int] NULL,
	[chaId_retorno_corresp] [int] NULL,
	[Chave] [varchar](50) NULL,
	[NF] [bigint] NULL,
	[cd_usuario_cadastro] [int] NULL,
	[lnfId] [int] NULL,
	[NFeRPS] [varchar](50) NULL,
	[vl_referenciaNF] [money] NULL,
	[dt_vencimento_new] [datetime] NULL,
	[obs] [varchar](500) NULL,
	[vl_imposto] [money] NULL,
	[vl_desconto_recebimento] [money] NULL,
	[vl_taxa] [money] NULL,
	[vl_titulo] [money] NULL,
	[vl_multa] [money] NULL,
	[dt_cancelado_contabil] [date] NULL,
	[VL_AcrescimoAvulso] [money] NULL,
	[VL_DescontoAvulso] [money] NULL,
	[VL_Final] [money] NULL,
	[linkNota] [varchar](300) NULL,
	[dt_negociado] [date] NULL,
	[obsNF] [varchar](500) NULL,
	[dt_credito] [datetime] NULL,
	[dt_emissao] [datetime] NULL,
	[cd_ParcelaOriginal] [int] NULL,
	[obsBoleto] [varchar](500) NULL,
	[dt_inicio_cobertura] [date] NULL,
	[cd_empresaGerado] [bigint] NULL,
	[executarTrigger] [bit] NULL,
	[cd_sequencial_lote_boleto] [int] NULL,
	[dentistaOrcamento] [int] NULL,
	[vendedorOrcamento] [int] NULL,
	[exibir] [bit] NULL,
	[cd_lote_processo_banco_baixa] [int] NULL,
	[dataRemessa] [datetime] NULL,
	[dt_visualizacaoNF] [datetime] NULL,
	[parcelaProtestada] [bit] NULL,
	[dataParcelaProtestada] [datetime] NULL,
	[usuarioParcelaProtestada] [int] NULL,
	[exigeNF] [bit] NULL,
	[dataPagamentoTerceiro] [datetime] NULL,
	[cd_lote_processo_acatado] [int] NULL,
	[dentistaExecutorOrcamento] [int] NULL,
	[cancelamentoNfe] [int] NULL,
	[data_confirmacao_recebimento] [datetime] NULL,
	[usuario_confirmacao_recebimento] [int] NULL,
	[origem_informacao_confirmacao] [int] NULL,
	[vl_pagoTerceiro] [money] NULL,
	[idIntegracaoExterna] [varchar](50) NULL,
	[cd_lote_processo_banco_recebido] [int] NULL,
	[nfeErro] [varchar](200) NULL,
 CONSTRAINT [PK_MENSALIDADES_1] PRIMARY KEY CLUSTERED 
(
	[CD_PARCELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_MENSALIDADES_5_1155183561__K8_K3_K2_K1_K6_K4_17] ON [dbo].[MENSALIDADES]
(
	[DT_VENCIMENTO] ASC,
	[TP_ASSOCIADO_EMPRESA] ASC,
	[CD_ASSOCIADO_empresa] ASC,
	[CD_PARCELA] ASC,
	[CD_TIPO_RECEBIMENTO] ASC,
	[cd_tipo_parcela] ASC
)
INCLUDE([VL_PAGO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_MENSALIDADES_7_1951306707__K6_K4_K9_K8] ON [dbo].[MENSALIDADES]
(
	[CD_TIPO_RECEBIMENTO] ASC,
	[cd_tipo_parcela] ASC,
	[DT_PAGAMENTO] ASC,
	[DT_VENCIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_MENSALIDADES_7_4819725__K8_K3_K6_K5_K1_K4_K2_K28_9_13_14_15_16_17] ON [dbo].[MENSALIDADES]
(
	[DT_VENCIMENTO] ASC,
	[TP_ASSOCIADO_EMPRESA] ASC,
	[CD_TIPO_RECEBIMENTO] ASC,
	[CD_TIPO_PAGAMENTO] ASC,
	[CD_PARCELA] ASC,
	[cd_tipo_parcela] ASC,
	[CD_ASSOCIADO_empresa] ASC,
	[lnfId] ASC
)
INCLUDE([DT_PAGAMENTO],[VL_PARCELA],[VL_Acrescimo],[VL_Desconto],[VL_SERVICO],[VL_PAGO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [_dta_index_MENSALIDADES_8_1321524237__K9_K3_K6_K4_K1_17] ON [dbo].[MENSALIDADES]
(
	[DT_PAGAMENTO] ASC,
	[TP_ASSOCIADO_EMPRESA] ASC,
	[CD_TIPO_RECEBIMENTO] ASC,
	[cd_tipo_parcela] ASC,
	[CD_PARCELA] ASC
)
INCLUDE([VL_PAGO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [i_mensalidades_02] ON [dbo].[MENSALIDADES]
(
	[CD_ASSOCIADO_empresa] ASC,
	[TP_ASSOCIADO_EMPRESA] ASC,
	[DT_VENCIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IN_Mensalidades_TP_ASSOCIADO_EMPRESA] ON [dbo].[MENSALIDADES]
(
	[TP_ASSOCIADO_EMPRESA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES] ON [dbo].[MENSALIDADES]
(
	[CD_ASSOCIADO_empresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_1] ON [dbo].[MENSALIDADES]
(
	[Chave] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_10] ON [dbo].[MENSALIDADES]
(
	[dataPagamentoTerceiro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_2] ON [dbo].[MENSALIDADES]
(
	[DT_VENCIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_3] ON [dbo].[MENSALIDADES]
(
	[DT_PAGAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_4] ON [dbo].[MENSALIDADES]
(
	[DT_VENCIMENTO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_5] ON [dbo].[MENSALIDADES]
(
	[DT_PAGAMENTO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_6] ON [dbo].[MENSALIDADES]
(
	[CD_TIPO_PAGAMENTO] ASC,
	[CD_TIPO_RECEBIMENTO] ASC,
	[DT_VENCIMENTO] ASC,
	[CD_PARCELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_7] ON [dbo].[MENSALIDADES]
(
	[NOSSO_NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_8] ON [dbo].[MENSALIDADES]
(
	[chaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_MENSALIDADES_9] ON [dbo].[MENSALIDADES]
(
	[lnfId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [MENSALIDADES_linkNota] ON [dbo].[MENSALIDADES]
(
	[linkNota] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[MENSALIDADES] ADD  CONSTRAINT [DF_MENSALIDADES_DT_GERADO]  DEFAULT (getdate()) FOR [DT_GERADO]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_MENSALIDADES_cd_sequencial_retorno] FOREIGN KEY([cd_lote_processo_acatado])
REFERENCES [dbo].[Lote_Processos_Bancos_Retorno] ([cd_sequencial_retorno])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_cd_sequencial_retorno]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_MENSALIDADES_EMPRESA] FOREIGN KEY([cd_empresaGerado])
REFERENCES [dbo].[EMPRESA] ([CD_EMPRESA])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_EMPRESA]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_MENSALIDADES_FUNCIONARIO_DENTISTA] FOREIGN KEY([dentistaOrcamento])
REFERENCES [dbo].[FUNCIONARIO] ([cd_funcionario])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_FUNCIONARIO_DENTISTA]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_MENSALIDADES_FUNCIONARIO_VENDEDOR] FOREIGN KEY([vendedorOrcamento])
REFERENCES [dbo].[FUNCIONARIO] ([cd_funcionario])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_FUNCIONARIO_VENDEDOR]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_MENSALIDADES_FUNCIONARIOProtesto] FOREIGN KEY([usuarioParcelaProtestada])
REFERENCES [dbo].[FUNCIONARIO] ([cd_funcionario])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_FUNCIONARIOProtesto]
ALTER TABLE [dbo].[MENSALIDADES]  WITH NOCHECK ADD  CONSTRAINT [FK_MENSALIDADES_TIPO_ASSOCIADO_EMPRESA] FOREIGN KEY([TP_ASSOCIADO_EMPRESA])
REFERENCES [dbo].[TIPO_ASSOCIADO_EMPRESA] ([TP_ASSOCIADO_EMPRESA])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_TIPO_ASSOCIADO_EMPRESA]
ALTER TABLE [dbo].[MENSALIDADES]  WITH NOCHECK ADD  CONSTRAINT [FK_MENSALIDADES_TIPO_PAGAMENTO] FOREIGN KEY([CD_TIPO_PAGAMENTO])
REFERENCES [dbo].[TIPO_PAGAMENTO] ([cd_tipo_pagamento])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_TIPO_PAGAMENTO]
ALTER TABLE [dbo].[MENSALIDADES]  WITH NOCHECK ADD  CONSTRAINT [FK_MENSALIDADES_TIPO_PAGAMENTO1] FOREIGN KEY([CD_TIPO_RECEBIMENTO])
REFERENCES [dbo].[TIPO_PAGAMENTO] ([cd_tipo_pagamento])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_TIPO_PAGAMENTO1]
ALTER TABLE [dbo].[MENSALIDADES]  WITH NOCHECK ADD  CONSTRAINT [FK_MENSALIDADES_Tipo_parcela] FOREIGN KEY([cd_tipo_parcela])
REFERENCES [dbo].[Tipo_parcela] ([cd_tipo_parcela])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_MENSALIDADES_Tipo_parcela]
ALTER TABLE [dbo].[MENSALIDADES]  WITH CHECK ADD  CONSTRAINT [FK_origem_confirmacao] FOREIGN KEY([origem_informacao_confirmacao])
REFERENCES [dbo].[TB_OrigemInformacao] ([cd_origeminformacao])
ALTER TABLE [dbo].[MENSALIDADES] CHECK CONSTRAINT [FK_origem_confirmacao]
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Parcela|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'CD_PARCELA'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Associado-Empresa' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'CD_ASSOCIADO_empresa'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tipo' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'TP_ASSOCIADO_EMPRESA'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tipo Parcela' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'cd_tipo_parcela'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tipo Pagamento' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'CD_TIPO_PAGAMENTO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tipo Recebimento' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'CD_TIPO_RECEBIMENTO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'NN|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'NOSSO_NUMERO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Data Vencimento|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'DT_VENCIMENTO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Data Pagamento|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'DT_PAGAMENTO'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Valor|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'VL_PARCELA'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Valor Pago|' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'VL_PAGO'
EXEC sys.sp_addextendedproperty @name=N'descricao_cancelamentoNfe', @value=N'NULL – Normal; -1 - Pendente para cancelamento; 1 - Cancelada; ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MENSALIDADES', @level2type=N'COLUMN',@level2name=N'cancelamentoNfe'
