/****** Object:  Table [dbo].[NotaFiscal_Mensalidade]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[NotaFiscal_Mensalidade](
	[nfpId] [int] IDENTITY(1,1) NOT NULL,
	[nfpNumero] [varchar](10) NULL,
	[nfpCodigoVerificacao] [varchar](10) NULL,
	[nfpDataEmissao] [datetime] NULL,
	[nfpBaseCalculo] [money] NULL,
	[nfpAliquota] [money] NULL,
	[nfpValorIss] [money] NULL,
	[nfpValorLiquidoNfse] [money] NULL,
	[nfpPrestadorCpfCnpj] [varchar](15) NULL,
	[nfpPrestadorInscricaoMunicipal] [varchar](15) NULL,
	[nfpPrestadorRazaoSocial] [varchar](200) NULL,
	[nfpPrestadorNomeFantasia] [varchar](60) NULL,
	[nfpPrestadorEndEndereco] [varchar](150) NULL,
	[nfpPrestadorEndNumero] [varchar](10) NULL,
	[nfpPrestadorEndComplemento] [varchar](60) NULL,
	[nfpPrestaddorEndBairro] [varchar](60) NULL,
	[nfpPrestadorEndCodigoMunicipio] [varchar](7) NULL,
	[nfpPrestadorEndUf] [varchar](2) NULL,
	[nfpPrestadorEndCodigoPais] [varchar](4) NULL,
	[nfpPrestadorEndCep] [varchar](8) NULL,
	[nfpPrestadorTelefone] [varchar](20) NULL,
	[nfpPrestadorEmail] [varchar](100) NULL,
	[nfpGeradorCodigoMunicipio] [varchar](7) NULL,
	[nfpGeradorUf] [varchar](2) NULL,
	[nfpRpsNumero] [varchar](20) NULL,
	[nfpRpsSerie] [varchar](10) NULL,
	[nfpRpsTipo] [varchar](1) NULL,
	[nfpRpsDataEmissao] [datetime] NULL,
	[nfpRpsStatus] [smallint] NULL,
	[nfpRpsCompetencia] [datetime] NULL,
	[nfpServicoValorServicos] [money] NULL,
	[nfpServicoValorDeducoes] [money] NULL,
	[nfpServicoValorPis] [money] NULL,
	[nfpServicoValorCofins] [money] NULL,
	[nfpServicoValorInss] [money] NULL,
	[nfpServicoValorIr] [money] NULL,
	[nfpServicoValorCsll] [money] NULL,
	[nfpServicoOutrasRetencoes] [money] NULL,
	[nfpServicoValorIss] [money] NULL,
	[nfpServicoAliquota] [money] NULL,
	[nfpServicoDescontoIncondicionado] [money] NULL,
	[nfpServicoDescontoCondicionado] [money] NULL,
	[nfpServicoIssRetido] [smallint] NULL,
	[nfpServicoItemListaServico] [varchar](10) NULL,
	[nfpServicoCodigoTributacaoMunicipio] [varchar](20) NULL,
	[nfpServicoDiscriminacao] [varchar](2000) NULL,
	[nfpServicoCodigoMunicipio] [varchar](7) NULL,
	[nfpServicoCodigoPais] [varchar](4) NULL,
	[nfpServicoExigibilidadeISS] [smallint] NULL,
	[nfpTomadorCpfCnpj] [varchar](14) NULL,
	[nfpTomadorRazaoSocial] [varchar](200) NULL,
	[nfpTomadorEndEndereco] [varchar](150) NULL,
	[nfpTomadorEndNumero] [varchar](10) NULL,
	[nfpTomadorEndComplemento] [varchar](60) NULL,
	[nfpTomadorEndBairro] [varchar](60) NULL,
	[nfpTomadorEndCodigoMunicipio] [varchar](7) NULL,
	[nfpTomadorEndUf] [varchar](7) NULL,
	[nfpTomadorEndCodigoPais] [varchar](4) NULL,
	[nfpTomadorEndCep] [varchar](8) NULL,
	[nfpTomadorTelefone] [varchar](20) NULL,
	[nfpTomadorEmail] [varchar](100) NULL,
	[nfpOptanteSimplesNacional] [smallint] NULL,
	[nfpIncentivoFiscal] [smallint] NULL,
	[Cd_parcela] [int] NULL,
	[nfpDt_Cadastro] [datetime] NULL,
 CONSTRAINT [PK_NotaFiscal_Mensalidade] PRIMARY KEY CLUSTERED 
(
	[nfpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[NotaFiscal_Mensalidade]  WITH CHECK ADD  CONSTRAINT [FK_NotaFiscal_Mensalidade_MENSALIDADES] FOREIGN KEY([Cd_parcela])
REFERENCES [dbo].[MENSALIDADES] ([CD_PARCELA])
ALTER TABLE [dbo].[NotaFiscal_Mensalidade] CHECK CONSTRAINT [FK_NotaFiscal_Mensalidade_MENSALIDADES]
