/****** Object:  Table [dbo].[PlanejamentoOrtodontico]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PlanejamentoOrtodontico](
	[porId] [int] IDENTITY(1,1) NOT NULL,
	[porTipoFacial] [varchar](50) NULL,
	[porDenticao] [varchar](50) NULL,
	[porClassificacaoAngle] [varchar](50) NULL,
	[porRelacaoCaninosDir] [varchar](50) NULL,
	[porRelacaoCaninosEsq] [varchar](50) NULL,
	[porLinhaMediana] [varchar](50) NULL,
	[porLinhaMedianaMandibula] [varchar](50) NULL,
	[porLinhaMedianaMandibulaMM] [varchar](50) NULL,
	[porLinhaMedianaMaxila] [varchar](50) NULL,
	[porLinhaMedianaMaxilaMM] [varchar](50) NULL,
	[porMordidaCruzada] [varchar](50) NULL,
	[porMordidaCruzadaOBS] [varchar](50) NULL,
	[porSobremordida] [varchar](50) NULL,
	[porSobremordidaAberta] [varchar](50) NULL,
	[porSobremordidaProfunda] [varchar](50) NULL,
	[porSobressaliencia] [varchar](50) NULL,
	[porPosicaoInc] [varchar](50) NULL,
	[porDiscrepanciaModelosSuperior] [varchar](50) NULL,
	[porDiscrepanciaModelosInferior] [varchar](50) NULL,
	[porATM] [varchar](50) NULL,
	[porATMOBS] [varchar](50) NULL,
	[porRespiracao] [varchar](50) NULL,
	[porDeglutinacao] [varchar](50) NULL,
	[porHabitos] [varchar](50) NULL,
	[porHabitosOBS] [varchar](50) NULL,
	[porDentesAusentes] [varchar](50) NULL,
	[porDentesSupranumerarios] [varchar](50) NULL,
	[porDentesRetidos] [varchar](50) NULL,
	[porDentesAgnedia] [varchar](50) NULL,
	[porPerda] [varchar](50) NULL,
	[porPerdaLocal] [varchar](50) NULL,
	[porReabsorcao] [varchar](50) NULL,
	[porReabsorcaoDentes] [varchar](50) NULL,
	[porFase] [varchar](50) NULL,
	[porExodontias] [varchar](50) NULL,
	[porExodontiasDentes] [varchar](50) NULL,
	[porDesgastesInterproximais] [varchar](50) NULL,
	[porDesgastesInterproximaisDentes] [varchar](50) NULL,
	[porAnconragem] [varchar](50) NULL,
	[porAnconragemRecurso] [varchar](50) NULL,
	[porPrognostico] [varchar](50) NULL,
	[porPrevisao1Fase] [varchar](50) NULL,
	[porPrevisao2Fase] [varchar](50) NULL,
	[porQueixaPaciente] [varchar](1000) NULL,
	[porObjetivo] [varchar](max) NULL,
	[porDtCadastro] [datetime] NULL,
	[cd_sequencial_dep] [int] NULL,
	[cd_funcionarioDentista] [int] NULL,
	[cd_filial] [int] NULL,
	[cd_funcionarioAnalise] [int] NULL,
	[porDtAnalise] [datetime] NULL,
	[porDtFinalizado] [datetime] NULL,
	[ArcadiaMedianaVertical] [varchar](20) NULL,
	[ArcadiaMedianaHorizontal] [varchar](20) NULL,
	[MordidaCruzadaDente] [varchar](20) NULL,
	[ArcadiaIncisivo] [varchar](20) NULL,
	[Quantidade] [int] NULL,
	[porDtAlteracao] [datetime] NULL,
	[RelacaoMolar] [varchar](50) NULL,
	[TipoMordidaCruzada] [varchar](20) NULL,
	[PosicaoMordidaCruzada] [varchar](20) NULL,
	[RelacaoVertical] [varchar](20) NULL,
	[LocalRelacaoVertical] [varchar](20) NULL,
	[PosicaoRelacaoVertical] [varchar](20) NULL,
	[SobressalienciaRelacaoVertical] [int] NULL,
	[DoencaPeriodontal] [varchar](20) NULL,
	[PerdaOssea] [varchar](20) NULL,
	[TipoPerdaOssea] [varchar](20) NULL,
	[DentesPerdaOssea] [varchar](50) NULL,
	[TipoAparelho] [varchar](200) NULL,
	[TecnicaOrtodontica] [varchar](200) NULL,
	[RelacaoMolarDireito] [varchar](50) NULL,
	[RelacaoMolarEsquerdo] [varchar](50) NULL,
	[porDtValidade] [datetime] NULL,
	[porMotivoFinalizado] [varchar](500) NULL,
	[cd_funcionarioFinalizado] [int] NULL,
	[porQuantidadeProcedimentoLiberado] [int] NULL,
 CONSTRAINT [PK_PlanejamentoOrtodontico] PRIMARY KEY CLUSTERED 
(
	[porId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[PlanejamentoOrtodontico]  WITH CHECK ADD  CONSTRAINT [FK_PlanejamentoOrtodontico_DEPENDENTES] FOREIGN KEY([cd_sequencial_dep])
REFERENCES [dbo].[DEPENDENTES] ([CD_SEQUENCIAL])
ALTER TABLE [dbo].[PlanejamentoOrtodontico] CHECK CONSTRAINT [FK_PlanejamentoOrtodontico_DEPENDENTES]
ALTER TABLE [dbo].[PlanejamentoOrtodontico]  WITH CHECK ADD  CONSTRAINT [FK_PlanejamentoOrtodontico_FILIAL] FOREIGN KEY([cd_filial])
REFERENCES [dbo].[FILIAL] ([cd_filial])
ALTER TABLE [dbo].[PlanejamentoOrtodontico] CHECK CONSTRAINT [FK_PlanejamentoOrtodontico_FILIAL]
