/****** Object:  Table [dbo].[PNL_TipoFila]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PNL_TipoFila](
	[cd_TipoFila] [int] IDENTITY(1,1) NOT NULL,
	[ds_TipoFila] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PNL_TipoFila1] PRIMARY KEY CLUSTERED 
(
	[cd_TipoFila] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
