/****** Object:  Table [dbo].[QuestionarioExameClinico]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[QuestionarioExameClinico](
	[qecId] [int] IDENTITY(1,1) NOT NULL,
	[cd_associado] [int] NOT NULL,
	[cd_sequencial_dep] [int] NOT NULL,
	[cd_funcionario] [int] NOT NULL,
	[cd_sequencial_agenda] [int] NULL,
	[qecDtCadastro] [datetime] NOT NULL,
	[qecTelefone] [varchar](11) NULL,
	[qecEmail] [varchar](100) NULL,
	[qecContatoUrgenciaNome] [varchar](50) NOT NULL,
	[qecContatoUrgenciaTelefone01] [varchar](11) NULL,
	[qecContatoUrgenciaTelefone02] [varchar](11) NULL,
	[qecHipertensao] [tinyint] NULL,
	[qecInsuficienciaCardiaca] [tinyint] NULL,
	[qecValvulopatia] [tinyint] NULL,
	[qecMarcapasso] [tinyint] NULL,
	[qecEndocarditeBacteriana] [tinyint] NULL,
	[qecInfartoAgudoMiocardio] [tinyint] NULL,
	[qecAsmaBronquica] [tinyint] NULL,
	[qecBronquite] [tinyint] NULL,
	[qecTuberculosePulmonar] [tinyint] NULL,
	[qecSinusite] [tinyint] NULL,
	[qecSincopes] [tinyint] NULL,
	[qecAVC] [tinyint] NULL,
	[qecConvulsoes] [tinyint] NULL,
	[qecDiabetes] [tinyint] NULL,
	[qecHiperlipidemia] [tinyint] NULL,
	[qecReposicaoHormonal] [tinyint] NULL,
	[qecAnemia] [tinyint] NULL,
	[qecHemofilia] [tinyint] NULL,
	[qecLeucemia] [tinyint] NULL,
	[qecGastrite] [tinyint] NULL,
	[qecUlcera] [tinyint] NULL,
	[qecCirrose] [tinyint] NULL,
	[qecHepatite] [tinyint] NULL,
	[qecHepatiteEspecificacao] [varchar](10) NULL,
	[qecDST] [tinyint] NULL,
	[qecHIV] [tinyint] NULL,
	[qecReumatismo] [tinyint] NULL,
	[qecOsteoporose] [tinyint] NULL,
	[qecOsteoporoseUtilizacaoMedicamento] [tinyint] NULL,
	[qecInsuficienciaRenal] [tinyint] NULL,
	[qecDialise] [tinyint] NULL,
	[qecArtriteReumatoide] [tinyint] NULL,
	[qecTransplantado] [tinyint] NULL,
	[qecCancer] [tinyint] NULL,
	[qecAlergiaAnestesicoLocal] [tinyint] NULL,
	[qecAlergiaAntibiotico] [tinyint] NULL,
	[qecAlergiaAnalgesico] [tinyint] NULL,
	[qecAlergiaAntiinflamatorio] [tinyint] NULL,
	[qecAlergiaAntiinflamatorioEspecificacao] [varchar](100) NULL,
	[qecUtilizacaoMedicamento] [tinyint] NULL,
	[qecUtilizacaoMedicamentoEspecificacao] [varchar](100) NULL,
	[qecAnestesiaGeral] [tinyint] NULL,
	[qecChoqueAnafilatico] [tinyint] NULL,
	[qecGravidez] [tinyint] NULL,
	[qecAmamentacao] [tinyint] NULL,
	[qecSangramentoExcessivo] [tinyint] NULL,
	[qecTabaco] [tinyint] NULL,
	[qecTabacoEspecificacao] [varchar](100) NULL,
	[qecTabacoConsumoDiario] [varchar](2) NULL,
	[qecTabacoTempoUtilizacao] [varchar](100) NULL,
	[qecTabacoEx] [tinyint] NULL,
	[qecTabacoTempoAbandono] [tinyint] NULL,
	[qecAlcool] [tinyint] NULL,
	[qecAlcoolTempoUtilizacao] [tinyint] NULL,
	[qecAlcoolEspecificacao] [varchar](100) NULL,
	[qecAlcoolConsumoDiario] [tinyint] NULL,
	[qecAlcoolEx] [tinyint] NULL,
	[qecAlcoolTempoAbandono] [tinyint] NULL,
	[qecAlcoolTempoDurante] [tinyint] NULL,
	[qecOutrasDrogas] [tinyint] NULL,
	[qecOutrasDrogasEspecificacao] [varchar](100) NULL,
	[qecDtExclusao] [datetime] NULL,
	[qecCardiopatias] [tinyint] NULL,
	[qecOUtros] [varchar](500) NULL,
 CONSTRAINT [PK_QuestionarioExameClinico] PRIMARY KEY CLUSTERED 
(
	[qecId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
