/****** Object:  Table [dbo].[REATipoTema]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REATipoTema](
	[rttId] [int] IDENTITY(1,1) NOT NULL,
	[rtiId] [tinyint] NOT NULL,
	[rteId] [tinyint] NOT NULL,
 CONSTRAINT [PK_REATipoTema] PRIMARY KEY CLUSTERED 
(
	[rttId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REATipoTema]  WITH CHECK ADD  CONSTRAINT [FK_REATipoTema_REATema] FOREIGN KEY([rteId])
REFERENCES [dbo].[REATema] ([rteId])
ALTER TABLE [dbo].[REATipoTema] CHECK CONSTRAINT [FK_REATipoTema_REATema]
ALTER TABLE [dbo].[REATipoTema]  WITH CHECK ADD  CONSTRAINT [FK_REATipoTema_REATipo] FOREIGN KEY([rtiId])
REFERENCES [dbo].[REATipo] ([rtiId])
ALTER TABLE [dbo].[REATipoTema] CHECK CONSTRAINT [FK_REATipoTema_REATipo]
