/****** Object:  Table [dbo].[TB_CEP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_CEP](
	[cd_sequencial_cep] [int] IDENTITY(1,1) NOT NULL,
	[CEPLOG] [varchar](8) NOT NULL,
	[LOGRADOURO] [nvarchar](80) NOT NULL,
	[CD_UF] [nvarchar](2) NULL,
	[CHAVE_TIPOLOGRADOURO] [int] NOT NULL,
	[COMPLELOG] [nvarchar](100) NULL,
	[NOME_BAIRRO] [varchar](80) NULL,
	[CD_MUNICIPIO] [int] NOT NULL,
	[cd_bairro] [int] NOT NULL,
	[fl_unico] [bit] NULL,
	[idRegiaoCep] [tinyint] NULL,
 CONSTRAINT [PK_TB_CEP] PRIMARY KEY CLUSTERED 
(
	[cd_sequencial_cep] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_TB_CEP] ON [dbo].[TB_CEP]
(
	[cd_bairro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TB_CEP_1] ON [dbo].[TB_CEP]
(
	[CD_MUNICIPIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TB_CEP_2] ON [dbo].[TB_CEP]
(
	[CEPLOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TB_CEP_3] ON [dbo].[TB_CEP]
(
	[CHAVE_TIPOLOGRADOURO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TB_CEP_4] ON [dbo].[TB_CEP]
(
	[LOGRADOURO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[TB_CEP]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_CEP_Bairro] FOREIGN KEY([cd_bairro])
REFERENCES [dbo].[Bairro] ([baiId])
ALTER TABLE [dbo].[TB_CEP] CHECK CONSTRAINT [FK_TB_CEP_Bairro]
ALTER TABLE [dbo].[TB_CEP]  WITH CHECK ADD  CONSTRAINT [FK_TB_CEP_idRegiaoCep] FOREIGN KEY([idRegiaoCep])
REFERENCES [dbo].[RegiaoCep] ([idRegiaoCep])
ALTER TABLE [dbo].[TB_CEP] CHECK CONSTRAINT [FK_TB_CEP_idRegiaoCep]
ALTER TABLE [dbo].[TB_CEP]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_CEP_MUNICIPIO] FOREIGN KEY([CD_MUNICIPIO])
REFERENCES [dbo].[MUNICIPIO] ([CD_MUNICIPIO])
ALTER TABLE [dbo].[TB_CEP] CHECK CONSTRAINT [FK_TB_CEP_MUNICIPIO]
ALTER TABLE [dbo].[TB_CEP]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_CEP_TB_TIPOLOGRADOURO] FOREIGN KEY([CHAVE_TIPOLOGRADOURO])
REFERENCES [dbo].[TB_TIPOLOGRADOURO] ([CHAVE_TIPOLOGRADOURO])
ALTER TABLE [dbo].[TB_CEP] CHECK CONSTRAINT [FK_TB_CEP_TB_TIPOLOGRADOURO]
