/****** Object:  Table [dbo].[TB_REGRA_SERVICO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_REGRA_SERVICO](
	[SEQUENCIAL_REGRASERVICO] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO_REGRA] [int] NOT NULL,
	[FACES] [varchar](100) NULL,
	[CD_SERVICO] [varchar](4000) NULL,
	[CD_UD] [varchar](4000) NULL,
	[CD_SERVICO2] [varchar](4000) NULL,
	[QT_Meses] [smallint] NULL,
	[Idade] [smallint] NULL,
	[Idade2] [smallint] NULL,
	[Numero] [smallint] NULL,
	[centro_custo] [varchar](500) NULL,
	[cd_plano] [varchar](200) NULL,
	[mensagemAmigavel] [varchar](4000) NULL,
	[plano] [varchar](4000) NULL,
 CONSTRAINT [PK_TB_REGRA_SERVICO] PRIMARY KEY CLUSTERED 
(
	[SEQUENCIAL_REGRASERVICO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TB_REGRA_SERVICO]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_REGRA_SERVICO_TB_REGRA] FOREIGN KEY([CODIGO_REGRA])
REFERENCES [dbo].[TB_REGRA] ([CODIGO_REGRA])
ALTER TABLE [dbo].[TB_REGRA_SERVICO] CHECK CONSTRAINT [FK_TB_REGRA_SERVICO_TB_REGRA]
