/****** Object:  Table [dbo].[TB_TIPOLOGRADOURO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TB_TIPOLOGRADOURO](
	[CHAVE_TIPOLOGRADOURO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_TIPO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TB_TIPOLOGRADOURO] PRIMARY KEY CLUSTERED 
(
	[CHAVE_TIPOLOGRADOURO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TB_TIPOLOGRADOURO] ON [dbo].[TB_TIPOLOGRADOURO]
(
	[NOME_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
