/****** Object:  Table [dbo].[TIPO_PAGAMENTO_MENSAGEM]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TIPO_PAGAMENTO_MENSAGEM](
	[CD_TIPO_PAGAMENTO] [int] NOT NULL,
	[NR_LINHA] [tinyint] NOT NULL,
	[MENSAGEM] [varchar](128) NULL,
	[cd_tipo_mensagem] [smallint] NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[TIPO_PAGAMENTO_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [FK_cd_tipo_mensagem] FOREIGN KEY([cd_tipo_mensagem])
REFERENCES [dbo].[tipo_mensagem] ([cd_tipo_mensagem])
ALTER TABLE [dbo].[TIPO_PAGAMENTO_MENSAGEM] CHECK CONSTRAINT [FK_cd_tipo_mensagem]
ALTER TABLE [dbo].[TIPO_PAGAMENTO_MENSAGEM]  WITH CHECK ADD  CONSTRAINT [FK_TIPO_PAGAMENTO_MENSAGEM_TIPO_PAGAMENTO] FOREIGN KEY([CD_TIPO_PAGAMENTO])
REFERENCES [dbo].[TIPO_PAGAMENTO] ([cd_tipo_pagamento])
ALTER TABLE [dbo].[TIPO_PAGAMENTO_MENSAGEM] CHECK CONSTRAINT [FK_TIPO_PAGAMENTO_MENSAGEM_TIPO_PAGAMENTO]
