/****** Object:  Table [dbo].[TIPO_ASSOCIADO_EMPRESA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TIPO_ASSOCIADO_EMPRESA](
	[TP_ASSOCIADO_EMPRESA] [smallint] NOT NULL,
	[DS_ASSOCIADO_EMPRESA] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TIPO_ASSOCIADO_EMPRESA] PRIMARY KEY CLUSTERED 
(
	[TP_ASSOCIADO_EMPRESA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
