/****** Object:  Table [dbo].[TISS_CBOS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TISS_CBOS](
	[REGISTRO] [int] NOT NULL,
	[CODIGO] [int] NOT NULL,
	[NOME] [varchar](100) NULL,
	[DESCRICAO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
